package model.helperView;

import java.util.ArrayList;
import java.util.List;

public class ListaDeIdiomas {

	private List<String> list;

	public ListaDeIdiomas() {

		list = new ArrayList<String>();

		list.add("Africâner – África do Sul");
		list.add("Africâner – Namíbia");
		list.add("Aimará – Bolívia");
		list.add("Aimará – Peru");
		list.add("Albanês – Albânia");
		list.add("Albanês – Kosovo");
		list.add("Albanês – Macedônia");
		list.add("Alemão – Áustria");
		list.add("Alemão – Alemanha");
		list.add("Alemão – Bélgica");
		list.add("Alemão – Liechtenstein");
		list.add("Alemão – Luxemburgo");
		list.add("Alemão – Suíça");
		list.add("Árabe – Argélia");
		list.add("Árabe – Bahrain");
		list.add("Árabe – Chade");
		list.add("Árabe – Comores");
		list.add("Árabe – Djibouti");
		list.add("Árabe – Egito");
		list.add("Árabe – Eritreia");
		list.add("Árabe – Iraque");
		list.add("Árabe – Israel");
		list.add("Árabe – Jordânia");
		list.add("Árabe – Kuwait");
		list.add("Árabe – Líbano");
		list.add("Árabe – Líbia");
		list.add("Árabe – Mauritânia");
		list.add("Árabe – Marrocos");
		list.add("Árabe – Omã");
		list.add("Árabe – Catar");
		list.add("Árabe – Arábia Saudita");
		list.add("Árabe – Somália");
		list.add("Árabe – Sudão");
		list.add("Árabe – Síria");
		list.add("Árabe – Emirados Árabes Unidos");
		list.add("Árabe – Tunísia");
		list.add("Árabe – Sara Ocidental");
		list.add("Árabe – Iêmen");
		list.add("Arménio – Armênia");
		list.add("Azeri – Azerbaijão");
		list.add("Bielorrusso – Bielorrússia");
		list.add("Bengali – Bangladesh");
		list.add("Bislama – Vanuatu");
		list.add("Bósnio – Bósnia e Herzegovina");
		list.add("Búlgaro – Bulgária");
		list.add("Cazaque – Cazaquistão");
		list.add("Catalão – Andorra");
		list.add("Checo – República Checa");
		list.add("Chinês Mandarim – China");
		list.add("Chinês Mandarim – Hong Kong");
		list.add("Chinês Mandarim – Macau");
		list.add("Chinês Mandarim – Taiwan");
		list.add("Chinês Mandarim – Malásia");
		list.add("Chinês Mandarim – Singapura");
		list.add("Coreano – Coreia do Norte");
		list.add("Coreano – Coreia do Sul");
		list.add("Croata – Bósnia e Herzegovina");
		list.add("Croata – Croácia");
		list.add("Curdo – Iraque");
		list.add("Dinamarquês – Dinamarca");
		list.add("Dinamarquês – Ilhas Feroé");
		list.add("Dinamarquês – Groenlândia");
		list.add("Dari – Afeganistão");
		list.add("Dhiveli – Maldivas");
		list.add("Dzongkha – Butão");
		list.add("Eslovaco – Eslováquia");
		list.add("Esloveno – Eslovênia");
		list.add("Espanhol – Argentina");
		list.add("Espanhol – Bolívia");
		list.add("Espanhol – Chile");
		list.add("Espanhol – Colômbia");
		list.add("Espanhol – Costa Rica");
		list.add("Espanhol – Cuba");
		list.add("Espanhol – República Dominicana");
		list.add("Espanhol – Equador");
		list.add("Espanhol – El Salvador");
		list.add("Espanhol – Espanha");
		list.add("Espanhol – Guiné Equatorial");
		list.add("Espanhol – Guatemala");
		list.add("Espanhol – Honduras");
		list.add("Espanhol – México");
		list.add("Espanhol – Nicarágua");
		list.add("Espanhol – Panamá");
		list.add("Espanhol – Paraguai");
		list.add("Espanhol – Peru");
		list.add("Espanhol – Porto Rico");
		list.add("Espanhol – Uruguai");
		list.add("Espanhol – Venezuela");
		list.add("Espanhol – Saara Ocidental");
		list.add("Estoniano – Estônia");
		list.add("Fijiano – Fiji");
		list.add("Filipino – Filipinas");
		list.add("Finlandês ou finês – Finlândia");
		list.add("Francês – Bélgica");
		list.add("Francês – Burkina Faso");
		list.add("Francês – Burundi");
		list.add("Francês – Camarões");
		list.add("Francês – Canadá");
		list.add("Francês – República Centro-Africana");
		list.add("Francês – Chade");
		list.add("Francês – Comores");
		list.add("Francês – Congo");
		list.add("Francês – Congo-Brazzaville");
		list.add("Francês – República Democrática do Congo");
		list.add("Francês – Congo-Kinshasa");
		list.add("Francês – Costa do Marfim");
		list.add("Francês – Djibuti");
		list.add("Francês – Guiné Equatorial");
		list.add("Francês – França");
		list.add("Francês – Gabão");
		list.add("Francês – Guiné");
		list.add("Francês – Haiti");
		list.add("Francês – Madagáscar");
		list.add("Francês – Mali");
		list.add("Francês – Maurícia");
		list.add("Francês – Mônaco");
		list.add("Francês – Ruanda");
		list.add("Francês – Senegal");
		list.add("Francês – Seychelles");
		list.add("Francês – Suíça");
		list.add("Francês – Togo");
		list.add("Francês – Vanuatu");
		list.add("Frísio – Países Baixos");
		list.add("Georgiano – Geórgia");
		list.add("Grego – Grécia");
		list.add("Grego – Chipre");
		list.add("Guarani – Paraguai");
		list.add("Crioulo haitiano – Haiti");
		list.add("Hebreu ou hebraico – Israel");
		list.add("Hindi – Índia");
		list.add("Hindi – Fiji");
		list.add("Hiri motu – Papua-Nova Guinélist.add");
		list.add("Holandês – Bélgica");
		list.add("Holandês – Países Baixos");
		list.add("Holandês – Suriname");
		list.add("Holandês – Antilhas Holandesas");
		list.add("Holandês – Aruba");
		list.add("Húngaro – Hungria");
		list.add("Indonésio – Indonésia");
		list.add("Inglês – Austrália");
		list.add("Inglês – Bahamas");
		list.add("Inglês – Belize");
		list.add("Inglês – Botsuana");
		list.add("Inglês – Canadá");
		list.add("Inglês – Estados Unidos");
		list.add("Inglês – Fiji");
		list.add("Inglês – Guiana");
		list.add("Inglês – Índia");
		list.add("Inglês – Quênia");
		list.add("Inglês – Kiribati");
		list.add("Inglês – Nigéria");
		list.add("Inglês – Paquistão");
		list.add("Inglês – Papua-Nova Guiné");
		list.add("Inglês – República da Irlanda");
		list.add("Inglês – África do Sul");
		list.add("Inglês – Nova Zelândia");
		list.add("Inglês – Malásia");
		list.add("Inglês – Singapura");
		list.add("Inglês – Filipinas");
		list.add("Inglês – Gâmbia");
		list.add("Inglês – Zâmbia");
		list.add("Inglês – Namíbia");
		list.add("Inglês – Trinidad e Tobago");
		list.add("Irlandês – República da Irlanda");
		list.add("Italiano – Itália");
		list.add("Italiano – Suíça");
		list.add("Italiano – San Marino");
		list.add("Italiano – Croácia");
		list.add("Italiano – Eslovênia");
		list.add("Japonês – Japão");
		list.add("Japonês – Palau");
		list.add("Canará – Índia");
		list.add("Khmer – Camboja");
		list.add("Laociano – Laos");
		list.add("Latim – Santa Sé (Cidade do Vaticano)");
		list.add("Letão – Letônia");
		list.add("Lituano – Lituânia");
		list.add("Macedônio – Macedônia");
		list.add("Malaio – Malásia");
		list.add("Malaio – Brunei");
		list.add("Malaio – Singapura");
		list.add("Malaiala – Índia");
		list.add("Maori – Nova Zelândia");
		list.add("Marata – Índia");
		list.add("Moldávio – Moldávia");
		list.add("Mongol – Mongólia");
		list.add("Mongol – China");
		list.add("Ndebele – África do Sul");
		list.add("Nepalês – Nepal");
		list.add("Sotho setentrional – África do Sul");
		list.add("Norueguês – Noruega");
		list.add("Oriá – Índia");
		list.add("Oriá – Orissa");
		list.add("Pachto – Afeganistão");
		list.add("Persa – Irã");
		list.add("Persa – Afeganistão");
		list.add("Persa – Tajiquistão");
		list.add("Polonês ou Polaco – Polônia");
		list.add("Português – Angola");
		list.add("Português – Brasil");
		list.add("Português – Cabo Verde");
		list.add("Português – Guiné-Bissau");
		list.add("Português – Macau");
		list.add("Português – Moçambique");
		list.add("Português – Portugal");
		list.add("Português – São Tomé e Príncipe");
		list.add("Português – Timor-Leste");
		list.add("Punjabi – Índia");
		list.add("Quíchua – Bolívia");
		list.add("Quíchua – Peru");
		list.add("Quirguiz – Quirguistão");
		list.add("Quirguiz – China");
		list.add("Romeno – Moldova");
		list.add("Romeno – Romênia");
		list.add("Romanche – Suíça");
		list.add("Russo – Ucrânia");
		list.add("Russo – Bielorrússia");
		list.add("Russo – Cazaquistão");
		list.add("Russo – Quirguizistão");
		list.add("Russo – Rússia");
		list.add("Sérvio – Bósnia e Herzegovina");
		list.add("Sérvio – Sérvia e Montenegro");
		list.add("Cingalês – Sri Lanka");
		list.add("Somali – Somália");
		list.add("Soto – África do Sul");
		list.add("Suaíli – Quênia");
		list.add("Suaíli – Tanzânia");
		list.add("Suázi – Suazilândia");
		list.add("Suázi – África do Sul");
		list.add("Sueco – Suécia");
		list.add("Tajique – Tajiquistão");
		list.add("Tâmil – Malásia");
		list.add("Tâmil – Singapura");
		list.add("Tâmil – Sri Lanka");
		list.add("Tétum – Timor-Leste");
		list.add("Tai – Tailândia");
		list.add("Tok Pisin – Papua-Nova Guiné");
		list.add("Tsonga – África do Sul");
		list.add("Tswana – África do Sul");
		list.add("Turco – Turquia");
		list.add("Turco – Chipre");
		list.add("Turcomeno – Turquemenistão");
		list.add("Ucraniano – Ucrânia");
		list.add("Uzbeque – Uzbequistão");
		list.add("Venda – África do Sul");
		list.add("Vietnamita – Vietname");
		list.add("Xhosa – África do Sul");
		list.add("Zulu – África do Sul");

	}

	public List<String> getList() {
		return list;
	}

	public void setList(List<String> list) {
		this.list = list;
	}
}
